In [ ]:
import sys
import os
import glob
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt 
import torch
print(f"CUDA Available: {torch.cuda.is_available()}")
time_to_date = lambda t: datetime.utcfromtimestamp(t).strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
def convert_to_int(x):
    if x == 0:
        return x
    elif isinstance(x, float) or isinstance(x, int):
        return x
    elif x.isnumeric():
        return int(x)
    elif x=='http':
        return 80
    elif x=='https':
        return 443
    elif x=='ntp':
        return 1023
    elif x=='mdns':
        return 5353
    elif x=='bootps':
        return 1234
    return 0

In [79]:
print("Current Directory:" + os.getcwd())
file_pattern = '*_stats.txt' # Use all pcap files
# file_pattern = '18-06-09_flows.txt'
glob_path = os.path.join('/users/grad/fali', 'benign', file_pattern)
file_list = glob.glob(glob_path)

li = []
for filepath in file_list:
    print(filepath)
    df = pd.read_csv(filepath, index_col=None, header=0, delimiter=',')
    li.append(df)

benign_flows = pd.concat(li, axis=0, ignore_index=True)


# benign_flows=benign_flows.fillna(0)

# benign_flows['Dport']=benign_flows['Dport'].apply(convert_to_int)
# benign_flows['Sport']=benign_flows['Sport'].apply(convert_to_int)

# def convert_string_to_int(x):
#     return abs(hash(x)) % (10 ** 10)
    
# string_features = ['Dir', 'DstAddr', 'SrcAddr', 'DstMac']

# for sf in string_features:
# #     benign_flows[sf]=benign_flows[sf].apply(convert_string_to_int)

%store benign_flows
benign_flows

Current Directory:/home/grad/fali/iot-packer
/users/grad/fali/benign/18-05-28_stats.txt
/users/grad/fali/benign/18-06-17_stats.txt
Stored 'benign_flows' (DataFrame)

,start,end,count,avergae_packet_size,syn_packets,synack_packets,ack_packets,data_packets,total_bytes,flow_count
0,1.527466e+09,1.527466e+09,312,792,0,0,237,153,247113,18
1,1.527466e+09,1.527466e+09,447,731,4,4,330,196,327092,22
2,1.527466e+09,1.527466e+09,383,686,5,4,262,180,262900,27
3,1.527466e+09,1.527466e+09,416,809,2,3,315,203,336646,16
4,1.527466e+09,1.527466e+09,307,824,1,1,233,153,253072,14
...,...,...,...,...,...,...,...,...,...,...
17275,1.529280e+09,1.529280e+09,121,221,3,3,59,54,26821,28
17276,1.529280e+09,1.529280e+09,124,232,4,4,62,56,28817,28
17277,1.529280e+09,1.529280e+09,194,253,8,8,98,65,49236,45
17278,1.529280e+09,1.529280e+09,106,209,4,4,48,45,22216,28
17279,1.529280e+09,1.529280e+09,86,0,2,2,40,41,21906,0

In [80]:
benign_flows.sum(axis = 0, skipna = True)

start                  2.641028e+13
end                    2.641028e+13
count                  5.563230e+06
avergae_packet_size    8.491977e+06
syn_packets            6.358700e+04
synack_packets         6.332400e+04
ack_packets            3.989996e+06
data_packets           2.387753e+06
total_bytes            3.650018e+09
flow_count             4.483880e+05
dtype: float64

In [81]:
import os
import glob
print("Current Directory:" + os.getcwd())
file_pattern = '*_stats.txt' # Use all pcap files
# file_pattern = '18-06-01_flows.txt'
glob_path = os.path.join('/users/grad/fali', 'attack', file_pattern)
file_list = glob.glob(glob_path)

li = []
for filepath in file_list:
    df = pd.read_csv(filepath, index_col=None, header=0, delimiter=',')
    li.append(df)

mixed_flows = pd.concat(li, axis=0, ignore_index=True)
all_flows=pd.concat([benign_flows, mixed_flows], axis=0)

mixed_flows

Current Directory:/home/grad/fali/iot-packer

,start,end,count,avergae_packet_size,syn_packets,synack_packets,ack_packets,data_packets,total_bytes,flow_count
0,1.528157e+09,1.528157e+09,356,770,4,3,264,162,274365,23
1,1.528157e+09,1.528157e+09,458,630,8,9,315,202,288741,42
2,1.528157e+09,1.528157e+09,416,708,3,3,307,190,294605,28
3,1.528157e+09,1.528157e+09,333,747,1,1,246,167,248782,20
4,1.528157e+09,1.528157e+09,389,718,4,4,280,182,279424,24
...,...,...,...,...,...,...,...,...,...,...
17254,1.528502e+09,1.528502e+09,136,289,3,3,71,64,39334,20
17255,1.528502e+09,1.528502e+09,102,247,3,3,49,47,25196,18
17256,1.528502e+09,1.528502e+09,96,206,3,2,46,39,19808,33
17257,1.528502e+09,1.528502e+09,157,194,5,6,70,71,30596,32
17258,1.528502e+09,1.528502e+09,3,0,0,0,0,1,512,0

In [82]:
# Load device_info from file
mac_to_filename = lambda s: f"{s.lower().replace(':', '')}.csv"

filepath = "/users/grad/fali/iot-traffic-analysis/device_info.csv"
device_info = pd.read_csv(filepath, index_col=None, delimiter=',')
device_info['annotation_file'] = device_info['mac'].map(mac_to_filename)
device_info

                 mac             ip         device_type   annotation_file
0  ec:1a:59:83:28:11  192.168.1.165  WEMO Motion Sensor  ec1a59832811.csv
1  ec:1a:59:79:f4:89  192.168.1.223   WEMO Power Switch  ec1a5979f489.csv
2  00:16:6c:ab:6b:88  192.168.1.248      Samsung Camera  00166cab6b88.csv
3  50:c7:bf:00:56:39  192.168.1.227        TP Link Plug  50c7bf005639.csv
4  70:ee:50:18:34:43  192.168.1.241      Netatmo Camera  70ee50183443.csv
5  00:17:88:2B:9A:25  192.168.1.129             Huebulb  0017882b9a25.csv
6  44:65:0D:56:CC:D3  192.168.1.239          AmazonEcho  44650d56ccd3.csv
7  F4:F5:D8:8F:0A:3C  192.168.1.119          chromecast  f4f5d88f0a3c.csv
8  74:C6:3B:29:D7:1D  192.168.1.163               ihome  74c63b29d71d.csv
9  D0:73:D5:01:83:08  192.168.1.118                lifx  d073d5018308.csv

In [83]:
file_pattern = '*.csv'
glob_path = os.path.join('/users/grad/fali/iot-traffic-analysis', 'annotations', file_pattern)
file_list = glob.glob(glob_path)

li = []
for filepath in file_list:
    print(f"loading {filepath}")
    df = pd.read_csv(filepath, index_col=None, delimiter=',', header=0, names=[
      'start_time', 'end_time', 'description', 'attack_type'])
    
    filename = os.path.basename(filepath)
    df['annotation_file'] = filename
    li.append(df)

all_known_attacks = pd.concat(li, axis=0, ignore_index=True)
# Convert time units to match tranalyzer
all_known_attacks.sort_values(by=['start_time'], inplace=True, ignore_index=True)
all_known_attacks["duration"] = all_known_attacks['end_time'] - all_known_attacks['start_time']

# Enrich attack meta-data with device meta-data
all_known_attacks = all_known_attacks.set_index('annotation_file').join(device_info.set_index('annotation_file'))
all_known_attacks.reset_index()

loading /users/grad/fali/iot-traffic-analysis/annotations/44650d56ccd3.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/ec1a59832811.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/d073d5018308.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/00166cab6b88.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/0017882b9a25.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/50c7bf005639.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/f4f5d88f0a3c.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/70ee50183443.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/ec1a5979f489.csv
loading /users/grad/fali/iot-traffic-analysis/annotations/74c63b29d71d.csv

,annotation_file,start_time,end_time,description,attack_type,duration,mac,ip,device_type
0,00166cab6b88.csv,1527835334,1527835936,Localfeatures|Allfeatures|Arpfeatures,ArpSpoof1L2D,602,00:16:6c:ab:6b:88,192.168.1.248,Samsung Camera
1,00166cab6b88.csv,1527836944,1527837544,Localfeatures|Allfeatures|Arpfeatures,ArpSpoof10L2D,600,00:16:6c:ab:6b:88,192.168.1.248,Samsung Camera
2,00166cab6b88.csv,1527860996,1527861596,localTcpPort49152|Tcpfeatures|Localfeatures|Al...,TcpSynDevice1L2D,600,00:16:6c:ab:6b:88,192.168.1.248,Samsung Camera
3,00166cab6b88.csv,1527862604,1527863204,localTcpPort49152|Tcpfeatures|Localfeatures|Al...,TcpSynDevice10L2D,600,00:16:6c:ab:6b:88,192.168.1.248,Samsung Camera
4,00166cab6b88.csv,1527864215,1527864815,localTcpPort49152|Tcpfeatures|Localfeatures|Al...,TcpSynDevice100L2D,600,00:16:6c:ab:6b:88,192.168.1.248,Samsung Camera
...,...,...,...,...,...,...,...,...,...
219,f4f5d88f0a3c.csv,1540314670,1540315270,Udpfeatures|Internetfeatures|Allfeatures|Inter...,Ssdp10W2D2W,600,F4:F5:D8:8F:0A:3C,192.168.1.119,chromecast
220,f4f5d88f0a3c.csv,1540315870,1540316470,Udpfeatures|Internetfeatures|Allfeatures|Inter...,Ssdp100W2D2W,600,F4:F5:D8:8F:0A:3C,192.168.1.119,chromecast
221,f4f5d88f0a3c.csv,1540452323,1540452924,Udpfeatures|Internetfeatures|Allfeatures|Inter...,Ssdp1W2D2W,601,F4:F5:D8:8F:0A:3C,192.168.1.119,chromecast
222,f4f5d88f0a3c.csv,1540453525,1540454125,Tcpfeatures|Internetfeatures|Allfeatures|Inter...,TcpSynReflection1W2D2W,600,F4:F5:D8:8F:0A:3C,192.168.1.119,chromecast
223,f4f5d88f0a3c.csv,1540462848,1540463448,Tcpfeatures|Internetfeatures|Allfeatures|Inter...,TcpSynReflection100W2D2W,600,F4:F5:D8:8F:0A:3C,192.168.1.119,chromecast

In [84]:
last_attack_endtime = max(all_known_attacks['end_time'])
last_flow_endtime = max(mixed_flows['start'])

print(f"last known attack ended at {time_to_date(last_attack_endtime)}")
print(f"last known flow ended at {time_to_date(last_flow_endtime)}")
# TODO - investigate why the last attack happens on Oct 25, but there are two more days of mixed traffic (Oct 26, Oct 27)

# Filter out attacks that happened outside our current dataset scope
known_attacks = all_known_attacks[all_known_attacks['end_time'] <= last_flow_endtime]
print(f"Using {len(known_attacks)} of {len(all_known_attacks)} known attacks")

last known attack ended at 2018-10-25 10:30:48
last known flow ended at 2018-06-08 23:56:11
Using 145 of 224 known attacks

In [88]:
# Apply IP and mac adress filters
attacker_ips = known_attacks.ip.unique()
attacker_macs = known_attacks.mac.unique()
attack_windows = [tuple(time_range) for time_range in known_attacks[['start_time', 'end_time']].values]
# matches_attack_address = (mixed_flows.srcIP.isin(attacker_ips)) | (mixed_flows.srcMac.isin(attacker_macs)) #| (mixed_flows.dstIP.isin(attacker_ips)) | (mixed_flows.dstMac.isin(attacker_macs))

# Apply attack window filters (capture flows that occured within a known attack)
attack_window_filters = [((attack.start_time <= mixed_flows.start ) & ( mixed_flows.end<=attack.end_time)) 
                         for i, attack in known_attacks.iterrows()]
in_any_attack_window = np.logical_or.reduce(attack_window_filters)

# Label traffic as attack or benign
# TODO - make sure only malicous flows are being captured by our filters

# for i, attack in known_attacks.iterrows():
# #     if ( attack.start_time <= 1528156799.463922) & (1528156809.463922 <= attack.end_time ):
# #         print(attack.start_time, attack.end_time)

mixed_flows.loc[:, 'is_attack'] = False
mixed_flows.loc[in_any_attack_window, 'is_attack'] = True

# Flow Counts ~ Mixed: 2280669, Benign: 886931, Attack: 1393738 # Filtering using srcIP, srcMac, dstIP, dstMac
# Flow Counts ~ Mixed: 2280669, Benign: 1450957, Attack: 829712 # Filtering using srcIP, srcMac
print(f"Flow Counts ~ Mixed: {len(mixed_flows)}, Benign: {(~mixed_flows.is_attack).sum()}, Attack: {(mixed_flows.is_attack).sum()}")

# for storing mixed flows
%store mixed_flows
mixed_flows

Flow Counts ~ Mixed: 17259, Benign: 16551, Attack: 708
Stored 'mixed_flows' (DataFrame)

,start,end,count,avergae_packet_size,syn_packets,synack_packets,ack_packets,data_packets,total_bytes,flow_count,is_attack
0,1.528157e+09,1.528157e+09,356,770,4,3,264,162,274365,23,False
1,1.528157e+09,1.528157e+09,458,630,8,9,315,202,288741,42,False
2,1.528157e+09,1.528157e+09,416,708,3,3,307,190,294605,28,False
3,1.528157e+09,1.528157e+09,333,747,1,1,246,167,248782,20,False
4,1.528157e+09,1.528157e+09,389,718,4,4,280,182,279424,24,False
...,...,...,...,...,...,...,...,...,...,...,...
17254,1.528502e+09,1.528502e+09,136,289,3,3,71,64,39334,20,False
17255,1.528502e+09,1.528502e+09,102,247,3,3,49,47,25196,18,False
17256,1.528502e+09,1.528502e+09,96,206,3,2,46,39,19808,33,False
17257,1.528502e+09,1.528502e+09,157,194,5,6,70,71,30596,32,False
17258,1.528502e+09,1.528502e+09,3,0,0,0,0,1,512,0,False

In [89]:
mixed_flows.is_attack.value_counts()

False    16551
True       708
Name: is_attack, dtype: int64

In [90]:
print("Listing features with a single uniform value (no information)")
print("Feature: unique value count")
print(all_flows.nunique()[all_flows.nunique() <= 1])

Listing features with a single uniform value (no information)
Feature: unique value count
Series([], dtype: int64)

In [91]:
features = ['count','avergae_packet_size','syn_packets','synack_packets','ack_packets','data_packets','total_bytes','flow_count']


labels = ['is_attack']
mixed_flows[features + labels]

# for storing features
%store features
print(f"Selected {len(features)} features")
features

Stored 'features' (list)
Selected 8 features

['count',
 'avergae_packet_size',
 'syn_packets',
 'synack_packets',
 'ack_packets',
 'data_packets',
 'total_bytes',
 'flow_count']